title: IEEE Hyderabad Section
description: >-
  The IEEE Hyderabad Section is one of the most active sections of IEEE in India.
  IEEE was formally introduced in Hyderabad, in June 1981, when a group of engineers
  in Hyderabad decided to form an IEEE sub-section here. This sub-section was rapidly 
  elevated to a full section, in 1984 (the year of IEEE Centenary celebrations).
url: "https://ieeehyderabad.org/"
navigation:
  - Home
  - Section:
    - IEEE Hyderabad Section
    - Policies
    - Future Directions
    - News Room
    - Announcements
    - Execom
    - Gallery
  - Sub-Sections:
    - Vizag Bay
    - Guntur (Amaravathi)
    - Ananthapur
  - Flagship Programs:
    - Conferences
    - IEEE Exhibits
    - Faraday Memorial Lectures (FML)
    - Section Student Congress (SSC)
    - Skill Connect
  - Chapters/AG:
    - CAS/EDS
    - CIS/GRSS
    - Computer Society
    - ComSoc/SPS
    - Education Society
    - MTT/AP/EMC
    - PES/IAS/PELS
    - Photonics
    - TEMS
    - Women in Engineering (WiE)
    - Young Professionals (YP)
  - Students:
    - Activities
    - Student Branches
    - Events
    - Benefits
    - Opportunities
  - Section Activities:
    - Section Newsletter
    - Section Minutes 
  - Upcoming Events
  - Misc:
    - FAQ
    - Content Instructions
    - Contact